"""Add extracted_skills, resume_vector, job_title

Revision ID: ed97b462741a
Revises: 
Create Date: 2025-11-02 23:29:03.131689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed97b462741a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('extracted_skills', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('resume_vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.add_column('resumes', sa.Column('job_title', sa.String(length=255), nullable=True, comment='Extracted job title'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'job_title')
    op.drop_column('resumes', 'resume_vector')
    op.drop_column('resumes', 'extracted_skills')
    # ### end Alembic commands ###
